DROP TABLE books CASCADE
DROP TABLE users CASCADE
DROP TABLE reviews CASCADE

CREATE TABLE books (
    id SERIAL PRIMARY KEY,
    isbn VARCHAR  UNIQUE NOT NULL,
    title VARCHAR NOT NULL,
    author VARCHAR NOT NULL,
    year INTEGER NOT NULL
);
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR UNIQUE NOT NULL,
    password VARCHAR NOT NULL,
    name VARCHAR NOT NULL
);
CREATE TABLE reviews (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users,
    book_id INTEGER REFERENCES books,
    review VARCHAR NOT NULL,
    rating INTEGER NOT NULL CHECK(rating >= 1 AND rating <= 5)
);